# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(blank=True, max_length=256, null=True)),
                ('content', models.TextField()),
                ('view_count', models.IntegerField(default=1)),
                ('comment_count', models.IntegerField(default=0)),
                ('ranking', models.IntegerField()),
                ('publish_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='bbs_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_nice', models.CharField(default='', max_length=64)),
                ('user_passwd', models.CharField(max_length=16)),
                ('user_signature', models.CharField(default='用户很懒,什么也没留下', max_length=128)),
                ('user_photo', models.ImageField(default='upload_imgs/user_default.jpg', upload_to='upload_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs01.bbs_user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('bbs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs01.bbs')),
                ('uesr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs01.bbs_user')),
            ],
        ),
        migrations.AddField(
            model_name='bbs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs01.bbs_user'),
        ),
        migrations.AddField(
            model_name='bbs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs01.category'),
        ),
    ]
